function report_stage(out, outdir)
% report_stage.m (v6.2)
% ---------------------------------------------------------
% Exports minimum artifacts for each pedagogical stage:
%   - 1 table (LaTeX) + >=1 figure
% and, for DR stages, additional risk-estimator diagnostics.
%
% This file is intentionally "lightweight" and toolbox-free.
% ---------------------------------------------------------

stage = out.stage;

% --- Stage 5: multi-scenario ---
if isstruct(out.res) && isfield(out.res,'A') && isfield(out.res,'B')
    scenarios = {'A','B','C','D'};

    % Table 1: arm MSE + policy MSE + final regret
    tex = {};
    tex{end+1} = sprintf('%% Auto-generated by report_stage.m (stage %d)', stage);
    tex{end+1} = '\\begin{tabular}{lcccccc}';
    tex{end+1} = '\\toprule';
    tex{end+1} = 'Scenario & Arm1 & Arm2 & Arm3 & Arm4 & Policy & FinalRegret \\\\';
    tex{end+1} = '\\midrule';
    for s=1:numel(scenarios)
        sc = scenarios{s};
        summ = out.res.(sc).summary;
        a = summ.arm_mse_mean;
        pm = summ.policy_mse_mean;
        fr = summ.final_regret_mean;
        tex{end+1} = sprintf('%s & %.3f & %.3f & %.3f & %.3f & %.3f & %.3f \\\\', sc, a(1),a(2),a(3),a(4),pm,fr);
    end
    tex{end+1} = '\\bottomrule';
    tex{end+1} = '\\end{tabular}';
    write_tex(fullfile(outdir, sprintf('tab_stage%d.tex', stage)), tex);

    % Table 2: DR risk bias by scenario (mean across arms)
    tex2 = {};
    tex2{end+1} = sprintf('%% Auto-generated by report_stage.m (stage %d) -- risk bias', stage);
    tex2{end+1} = '\\begin{tabular}{lccc}';
    tex2{end+1} = '\\toprule';
    tex2{end+1} = 'Scenario & Bias(DR) & Bias(IPW) & Bias(OR) \\\\';
    tex2{end+1} = '\\midrule';
    for s=1:numel(scenarios)
        sc = scenarios{s};
        summ = out.res.(sc).summary;
        bdr  = mean(summ.risk_bias_dr_mean(~isnan(summ.risk_bias_dr_mean)));
        bipw = mean(summ.risk_bias_ipw_mean(~isnan(summ.risk_bias_ipw_mean)));
        bor  = mean(summ.risk_bias_or_mean(~isnan(summ.risk_bias_or_mean)));
        tex2{end+1} = sprintf('%s & %.3f & %.3f & %.3f \\\\', sc, bdr, bipw, bor);
    end
    tex2{end+1} = '\\bottomrule';
    tex2{end+1} = '\\end{tabular}';
    write_tex(fullfile(outdir, sprintf('tab_stage%d_riskbias.tex', stage)), tex2);

    % Figure: policy MSE by scenario
    vals = zeros(numel(scenarios),1);
    for s=1:numel(scenarios)
        vals(s) = out.res.(scenarios{s}).summary.policy_mse_mean;
    end
    f = figure('Visible','off');
    bar(vals);
    set(gca,'XTickLabel',scenarios);
    ylabel('Policy MSE');
    title(sprintf('Stage %d: policy MSE across scenarios', stage));
    saveas(f, fullfile(outdir, sprintf('fig_stage%d_policy_mse.png', stage)));
    close(f);

    % Figure: mean DR bias by scenario
    vals2 = zeros(numel(scenarios),1);
    for s=1:numel(scenarios)
        summ = out.res.(scenarios{s}).summary;
        vals2(s) = mean(summ.risk_bias_dr_mean(~isnan(summ.risk_bias_dr_mean)));
    end
    g = figure('Visible','off');
    bar(vals2);
    set(gca,'XTickLabel',scenarios);
    ylabel('Mean bias (DR risk)');
    title(sprintf('Stage %d: mean DR risk bias across scenarios', stage));
    saveas(g, fullfile(outdir, sprintf('fig_stage%d_dr_bias.png', stage)));
    close(g);

    return;
end

% --- Single result ---
res = out.res;
summ = res.summary;

% Table 1: core metrics (always)
tex = {};
tex{end+1} = sprintf('%% Auto-generated by report_stage.m (stage %d)', stage);
tex{end+1} = '\\begin{tabular}{lcccc}';
tex{end+1} = '\\toprule';
tex{end+1} = ' & Arm1 & Arm2 & Arm3 & Arm4 \\\\';
tex{end+1} = '\\midrule';
tex{end+1} = sprintf('MSE (mean) & %.3f & %.3f & %.3f & %.3f \\\\', summ.arm_mse_mean(1), summ.arm_mse_mean(2), summ.arm_mse_mean(3), summ.arm_mse_mean(4));
if ~isnan(summ.policy_mse_mean)
    tex{end+1} = sprintf('Policy MSE (mean) & \\multicolumn{4}{c}{%.3f} \\\\', summ.policy_mse_mean);
end
if ~isnan(summ.final_regret_mean)
    tex{end+1} = sprintf('Final revealed regret (mean) & \\multicolumn{4}{c}{%.3f} \\\\', summ.final_regret_mean);
end
tex{end+1} = '\\bottomrule';
tex{end+1} = '\\end{tabular}';
write_tex(fullfile(outdir, sprintf('tab_stage%d.tex', stage)), tex);

% Table 2: risk estimator bias (DR stages only)
if isfield(summ,'risk_bias_dr_mean') && ~all(isnan(summ.risk_bias_dr_mean))
    tex2 = {};
    tex2{end+1} = sprintf('%% Auto-generated by report_stage.m (stage %d) -- risk bias', stage);
    tex2{end+1} = '\\begin{tabular}{lccc}';
    tex2{end+1} = '\\toprule';
    tex2{end+1} = 'Arm & Bias(DR) & Bias(IPW) & Bias(OR) \\\\';
    tex2{end+1} = '\\midrule';
    for k=1:4
        tex2{end+1} = sprintf('%d & %.3f & %.3f & %.3f \\\\', k, summ.risk_bias_dr_mean(k), summ.risk_bias_ipw_mean(k), summ.risk_bias_or_mean(k));
    end
    tex2{end+1} = '\\bottomrule';
    tex2{end+1} = '\\end{tabular}';
    write_tex(fullfile(outdir, sprintf('tab_stage%d_riskbias.tex', stage)), tex2);
end

% --- Figure 1: arm MSE bar + policy level (avoid yline for compatibility) ---
f = figure('Visible','off');
bar(summ.arm_mse_mean);
hold on;
if ~isnan(summ.policy_mse_mean)
    plot([0.5 4.5], [summ.policy_mse_mean summ.policy_mse_mean], 'k--', 'LineWidth', 1.0);
end
xlabel('Arm');
ylabel('MSE');
title(sprintf('Stage %d: mean MSE by arm', stage));
saveas(f, fullfile(outdir, sprintf('fig_stage%d_arm_mse.png', stage)));
close(f);

% --- Figure 2: regret path from first replication (if available) ---
if ~isempty(res.rep) && isfield(res.rep{1},'algo') && isfield(res.rep{1}.algo,'regret_revealed')
    rr = res.rep{1}.algo.regret_revealed;
    if ~isempty(rr) && ~all(isnan(rr))
        g = figure('Visible','off');
        plot(rr,'-o');
        xlabel('Batch b');
        ylabel('Revealed regret');
        title(sprintf('Stage %d: revealed regret path (rep 1)', stage));
        saveas(g, fullfile(outdir, sprintf('fig_stage%d_regret_path.png', stage)));
        close(g);
    end
end

% --- Figure 3: DR risk estimates over batches (if available) ---
if ~isempty(res.rep) && isfield(res.rep{1},'algo') && isfield(res.rep{1}.algo,'Rhat_dr_batch')
    Rb = res.rep{1}.algo.Rhat_dr_batch;
    if ~isempty(Rb) && ~all(isnan(Rb(:)))
        h = figure('Visible','off');
        plot(Rb'); % each arm path
        xlabel('Batch b');
        ylabel('Estimated risk (DR)');
        title(sprintf('Stage %d: batch-wise DR risk estimates (rep 1)', stage));
        legend({'Arm1','Arm2','Arm3','Arm4'}, 'Location','best');
        saveas(h, fullfile(outdir, sprintf('fig_stage%d_dr_risk_path.png', stage)));
        close(h);
    end
end

% --- Figure 4: overall arm selection shares (if available) ---
if ~isempty(res.rep) && isfield(res.rep{1},'algo') && isfield(res.rep{1}.algo,'action')
    a = res.rep{1}.algo.action;
    if ~isempty(a)
        shares = zeros(4,1);
        for k=1:4
            shares(k) = mean(a(~isnan(a))==k);
        end
        sfig = figure('Visible','off');
        bar(shares);
        xlabel('Arm');
        ylabel('Selection share');
        title(sprintf('Stage %d: arm selection shares (rep 1)', stage));
        saveas(sfig, fullfile(outdir, sprintf('fig_stage%d_arm_shares.png', stage)));
        close(sfig);
    end
end


% --- Extra diagnostics for context stages: mean per-batch shares and MSE ---
if stage >= 6 && ~isempty(res.rep) && isfield(res.rep{1},'algo') ...
        && isfield(res.rep{1}.algo,'I_batches') ...
        && isfield(res.rep{1},'Y_true') ...
        && isfield(res.rep{1},'action_mask') ...
        && isfield(res.rep{1}.algo,'yhat_store')

    R = numel(res.rep);
    I_batches = res.rep{1}.algo.I_batches;
    B = numel(I_batches);
    K = size(res.rep{1}.algo.yhat_store, 2);

    % best static arm (k*) from Monte Carlo summary
    [~, kstar] = min(res.summary.arm_mse_mean);

    share_mean = zeros(B,K);
    mse_pol_mean = zeros(B,1);
    mse_sta_mean = zeros(B,1);

    for b=1:B
        sh_acc = zeros(R,K);
        mp_acc = zeros(R,1);
        ms_acc = zeros(R,1);

        for rr=1:R
            rep = res.rep{rr};
            algo = rep.algo;

            amask = rep.action_mask(:);
            idxB = algo.I_batches{b};
            idxB = idxB(amask(idxB));

            a = algo.action(:);
            ystore = algo.yhat_store;
            Ytrue = rep.Y_true(:);

            % shares
            for k=1:K
                sh_acc(rr,k) = mean(a(idxB)==k, 'omitnan');
            end

            % MSE policy vs best static on idxB
            kk = a(idxB);
            good = ~isnan(kk);
            ii = idxB(good);
            kk = kk(good);

            if ~isempty(ii)
                lin = sub2ind(size(ystore), ii, kk);
                ypol = ystore(lin);
                ysta = ystore(ii, kstar);

                mp_acc(rr) = mean((ypol - Ytrue(ii)).^2, 'omitnan');
                ms_acc(rr) = mean((ysta - Ytrue(ii)).^2, 'omitnan');
            else
                mp_acc(rr) = NaN;
                ms_acc(rr) = NaN;
            end
        end

        share_mean(b,:) = mean(sh_acc, 1, 'omitnan');
        mse_pol_mean(b) = mean(mp_acc, 1, 'omitnan');
        mse_sta_mean(b) = mean(ms_acc, 1, 'omitnan');
    end

    % Figure: mean shares by batch
    f1 = figure('Visible','off');
    plot(share_mean, '-o');
    grid on;
    xlabel('batch');
    ylabel('mean share (across reps)');
    title(sprintf('Stage %d: mean arm shares per batch', stage));
    legend(arrayfun(@(k) sprintf('arm%d',k), 1:K, 'UniformOutput', false), 'Location', 'best');
    saveas(f1, fullfile(outdir, sprintf('fig_stage%d_mean_arm_shares_by_batch.png', stage)));
    close(f1);

    % Figure: mean MSE by batch (policy vs best static)
    f2 = figure('Visible','off');
    plot(mse_pol_mean, '-o'); hold on;
    plot(mse_sta_mean, '-o');
    grid on;
    xlabel('batch');
    ylabel('MSE in batch');
    title(sprintf('Stage %d: mean MSE per batch (policy vs best static)', stage));
    legend('Policy','Best static (k*)','Location','best');
    saveas(f2, fullfile(outdir, sprintf('fig_stage%d_mean_mse_by_batch.png', stage)));
    close(f2);

    % --- Stage 7 only: group-wise diagnostics for the E2 two-regime design ---
    if stage==7 && isfield(res.rep{1},'lambda_true')
        stage7_group_diagnostics(res, outdir);
    end
end

end

function stage7_group_diagnostics(res, outdir)
% stage7_group_diagnostics (local to report_stage.m)
% ---------------------------------------------------------
% For scenario E2 we want a true "context matters" outcome:
% the best imputer differs by regime.
%
% Regimes are defined by \lambda_i above/below its sample median.
% This routine exports:
%   (i) group-wise MSE by arm + policy (table + figure)
%   (ii) group-wise selection shares (table + figure)
% ---------------------------------------------------------

R = numel(res.rep);
K = size(res.rep{1}.algo.yhat_store,2);
T = size(res.rep{1}.Y_true,2);

mse_arm_L = zeros(R,K);
mse_arm_H = zeros(R,K);
mse_pol_L = zeros(R,1);
mse_pol_H = zeros(R,1);
share_L = zeros(R,K);
share_H = zeros(R,K);

for rr=1:R
    rep = res.rep{rr};
    algo = rep.algo;

    lambda = rep.lambda_true(:);
    med = median(lambda);
    gH = (lambda >= med);
    gHcell = repmat(gH, 1, T);
    gLcell = ~gHcell;

    amask = rep.action_mask;
    a = algo.action;
    ystore = algo.yhat_store;
    Ytrue = rep.Y_true;

    idxL = find(amask & gLcell);
    idxH = find(amask & gHcell);

    % Arm MSE ("as if" each arm were used within the group)
    for k=1:K
        yk = ystore(:,k);
        mse_arm_L(rr,k) = mean((yk(idxL) - Ytrue(idxL)).^2, 'omitnan');
        mse_arm_H(rr,k) = mean((yk(idxH) - Ytrue(idxH)).^2, 'omitnan');
    end

    % Policy MSE within each group
    kkL = a(idxL);
    goodL = ~isnan(kkL);
    iiL = idxL(goodL);
    kkL = kkL(goodL);
    if ~isempty(iiL)
        linL = sub2ind(size(ystore), iiL, kkL);
        ypolL = ystore(linL);
        mse_pol_L(rr) = mean((ypolL - Ytrue(iiL)).^2, 'omitnan');
    else
        mse_pol_L(rr) = NaN;
    end

    kkH = a(idxH);
    goodH = ~isnan(kkH);
    iiH = idxH(goodH);
    kkH = kkH(goodH);
    if ~isempty(iiH)
        linH = sub2ind(size(ystore), iiH, kkH);
        ypolH = ystore(linH);
        mse_pol_H(rr) = mean((ypolH - Ytrue(iiH)).^2, 'omitnan');
    else
        mse_pol_H(rr) = NaN;
    end

    % Selection shares within each group
    for k=1:K
        share_L(rr,k) = mean(a(idxL)==k, 'omitnan');
        share_H(rr,k) = mean(a(idxH)==k, 'omitnan');
    end
end

mseL = mean(mse_arm_L, 1, 'omitnan');
mseH = mean(mse_arm_H, 1, 'omitnan');
polL = mean(mse_pol_L, 'omitnan');
polH = mean(mse_pol_H, 'omitnan');
shL  = mean(share_L, 1, 'omitnan');
shH  = mean(share_H, 1, 'omitnan');

% --- Table: group-wise MSE ---
tex = {};
tex{end+1} = '% Auto-generated by report_stage.m (stage 7) -- group diagnostics';
% IMPORTANT: In MATLAB strings, LaTeX backslashes must be escaped.
% Use '\\' in MATLAB to print '\' in the .tex file.
tex{end+1} = '\\begin{tabular}{lccccc}';
tex{end+1} = '\\toprule';
tex{end+1} = 'Group & Arm1 & Arm2 & Arm3 & Arm4 & Policy \\\\';
tex{end+1} = '\\midrule';
tex{end+1} = sprintf('Low-$\\lambda$ & %.3f & %.3f & %.3f & %.3f & %.3f \\\\', mseL(1),mseL(2),mseL(3),mseL(4), polL);
tex{end+1} = sprintf('High-$\\lambda$ & %.3f & %.3f & %.3f & %.3f & %.3f \\\\', mseH(1),mseH(2),mseH(3),mseH(4), polH);
tex{end+1} = '\\bottomrule';
tex{end+1} = '\\end{tabular}';
write_tex(fullfile(outdir,'tab_stage7_groups.tex'), tex);

% --- Figure: group-wise MSE by arm (grouped bars) ---
f = figure('Visible','off');
hb = bar([mseL(:) mseH(:)]);
hold on;
h1 = plot([0.5 4.5],[polL polL],'k--','LineWidth',1.0);
h2 = plot([0.5 4.5],[polH polH],'k:','LineWidth',1.0);
xlabel('Arm');
ylabel('MSE');
title('Stage 7: group-wise MSE by arm (policy lines)');
legend([hb(1) hb(2) h1 h2], {'Low-\lambda','High-\lambda','Policy (Low)','Policy (High)'}, 'Location','best');
saveas(f, fullfile(outdir,'fig_stage7_group_mse.png'));
close(f);

% --- Table: group-wise selection shares ---
tex2 = {};
tex2{end+1} = '% Auto-generated by report_stage.m (stage 7) -- group selection shares';
tex2{end+1} = '\\begin{tabular}{lcccc}';
tex2{end+1} = '\\toprule';
tex2{end+1} = 'Group & Arm1 & Arm2 & Arm3 & Arm4 \\\\';
tex2{end+1} = '\\midrule';
tex2{end+1} = sprintf('Low-$\\lambda$ & %.3f & %.3f & %.3f & %.3f \\\\', shL(1),shL(2),shL(3),shL(4));
tex2{end+1} = sprintf('High-$\\lambda$ & %.3f & %.3f & %.3f & %.3f \\\\', shH(1),shH(2),shH(3),shH(4));
tex2{end+1} = '\\bottomrule';
tex2{end+1} = '\\end{tabular}';
write_tex(fullfile(outdir,'tab_stage7_groups_shares.tex'), tex2);

% --- Figure: group-wise selection shares ---
g = figure('Visible','off');
bar([shL(:) shH(:)]);
xlabel('Arm');
ylabel('Selection share');
title('Stage 7: group-wise arm selection shares');
legend({'Low-\lambda','High-\lambda'}, 'Location','best');
saveas(g, fullfile(outdir,'fig_stage7_group_shares.png'));
close(g);

end

function write_tex(path, lines)
fid = fopen(path,'w');
for j=1:numel(lines)
    fprintf(fid,'%s\n', lines{j});
end
fclose(fid);
end
